package com.vipercode.ide.util

import com.vipercode.ide.data.prefs.SettingsRepository
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow

/**
 * Centralised, in-memory i18n layer for ViperCode.
 *
 * Added in v0.0.4 — the app ships with two languages: English (default)
 * and Vietnamese (Tiếng Việt). All UI strings go through [Strings.get]
 * so a single preference flip re-renders the whole app in the chosen
 * language without an Activity restart.
 *
 * The active language is published via a [StateFlow] so any composable
 * calling [Strings.get] inside a `collectAsState`-driven read will
 * recompose when the language changes.
 *
 * v0.0.4 keeps the implementation dependency-free (no Android resource
 * system, no ICU) so the runtime cost is a hashmap lookup. Adding a new
 * language is a one-step change: append a [Language] variant, fill in
 * the [STRINGS] map, and the rest of the app picks it up automatically.
 */
object Strings {

    enum class Language(val displayName: String, val nativeName: String) {
        ENGLISH("English", "English"),
        VIETNAMESE("Tiếng Việt", "Tiếng Việt"),
    }

    /**
     * The full string catalogue. Every key the app uses lives here so we
     * have a single source of truth — adding a new string is one entry
     * per language and the compiler will surface any missing key at the
     * call site (because [T] is a typed property, not a string lookup).
     */
    data class T(
        // App
        val appName: String,
        val tagline: String,
        // Splash
        val splashLoading: String,
        // Home
        val homeNoFolder: String,
        val homePickFolder: String,
        val homeNewFile: String,
        val homeNewFolder: String,
        val homeNewFileHere: String,
        val homeNewFolderHere: String,
        val homeRefresh: String,
        val homeOpenFolderSaf: String,
        val homeUseLocalWorkspace: String,
        val homeSettings: String,
        val homeAbout: String,
        val homeRecent: String,
        val homeNoRecent: String,
        val homeClearRecent: String,
        val homeUploadZip: String,
        val homeSwitchFolder: String,
        val homeProjects: String,
        val homeNoProjects: String,
        val homeFolderSectionWorkspace: String,
        val homeFolderSectionProjects: String,
        val homeFolderSectionRecent: String,
        val homeFolderSectionDevice: String,
        val homeBrowseDevice: String,
        val homeExtractingZip: String,
        val homeZipExtracted: String,
        val homeZipExtractFailed: String,
        val homeZipInvalid: String,
        val homeEmptyFolder: String,
        val homeEmptyFolderHint: String,
        val homeCurrentFolder: String,
        // Dialogs
        val dialogNewFileTitle: String,
        val dialogNewFileHint: String,
        val dialogNewFolderTitle: String,
        val dialogNewFolderHint: String,
        val dialogChooseAction: String,
        val dialogRename: String,
        val dialogDelete: String,
        val dialogDuplicate: String,
        val dialogCreate: String,
        val dialogCancel: String,
        val dialogConfirmDelete: String,
        val dialogUnsavedTitle: String,
        val dialogUnsavedBody: String,
        val dialogSave: String,
        val dialogDiscard: String,
        val dialogGoToLineTitle: String,
        val dialogGoToLineHint: String,
        val dialogQuickOpenTitle: String,
        val dialogSearchInFilesTitle: String,
        val dialogSearchInFilesHint: String,
        // v0.0.8 — new strings for the command palette + line ops
        // + autocomplete. (Existing settings strings like
        // settingsLineNumbers / settingsWordWrap / settingsAutoIndent /
        // settingsAutoCloseBrackets are reused — not redeclared here.)
        val dialogCommandPaletteTitle: String,
        val dialogCommandPaletteHint: String,
        val editorMoveLineUp: String,
        val editorMoveLineDown: String,
        val editorDuplicateLine: String,
        val editorDeleteLine: String,
        val editorCommandPalette: String,
        val editorAutocompleteEnabled: String,
        val settingsAutocomplete: String,
        // Editor
        val editorEmpty: String,
        val editorSave: String,
        val editorSaved: String,
        val editorSaveFailed: String,
        val editorSearch: String,
        val editorLivePreview: String,
        val editorBack: String,
        val editorCloseTab: String,
        val editorReadOnly: String,
        val editorFind: String,
        val editorReplace: String,
        val editorReplaceAll: String,
        val editorReplaceCurrent: String,
        val editorNoMatchToReplace: String,
        val editorNoMatchesToReplace: String,
        val editorPreviousMatch: String,
        val editorNextMatch: String,
        val editorCloseSearch: String,
        val editorReplacedMatchN: String,
        val editorReplacedNOccurrences: String,
        val editorGoToLine: String,
        val editorQuickOpen: String,
        val editorSearchInFiles: String,
        val editorWordWrap: String,
        val editorShowLineNumbers: String,
        val editorAutoIndent: String,
        val editorShare: String,
        val editorShareFailed: String,
        val editorCommentToggle: String,
        val editorUndo: String,
        val editorRedo: String,
        val editorLines: String,
        val editorWords: String,
        val editorChars: String,
        val editorCursor: String,
        val editorSelected: String,
        // Preview
        val previewTitle: String,
        val previewSubtitle: String,
        val previewEmpty: String,
        val previewBackToEditor: String,
        val previewReload: String,
        val previewLiveToggle: String,
        val previewConsole: String,
        val previewConsoleEmpty: String,
        val previewClearConsole: String,
        val previewShare: String,
        val previewShareFailed: String,
        val previewOpenExternal: String,
        val previewDesktopView: String,
        val previewMobileView: String,
        val previewMarkdown: String,
        val previewNoPreview: String,
        // Settings
        val settingsTitle: String,
        val settingsAppearance: String,
        val settingsLanguage: String,
        val settingsLanguageDesc: String,
        val settingsTheme: String,
        val settingsThemeSystem: String,
        val settingsThemeDark: String,
        val settingsThemeLight: String,
        val settingsDynamicColor: String,
        val settingsDynamicColorDesc: String,
        val settingsEditor: String,
        val settingsFontSize: String,
        val settingsTabSize: String,
        val settingsTabSizeValue: String,
        val settingsWordWrap: String,
        val settingsWordWrapDesc: String,
        val settingsLineNumbers: String,
        val settingsLineNumbersDesc: String,
        val settingsAutoIndent: String,
        val settingsAutoIndentDesc: String,
        val settingsAutoSave: String,
        val settingsAutoSaveDesc: String,
        val settingsAutoSaveDelay: String,
        val settingsFontFamily: String,
        val settingsStorage: String,
        val settingsUseLocalWorkspace: String,
        val settingsUseLocalWorkspaceDesc: String,
        val settingsHiddenFiles: String,
        val settingsHiddenFilesDesc: String,
        val settingsAutoCloseBrackets: String,
        val settingsAutoCloseBracketsDesc: String,
        val settingsShowStatusBar: String,
        val settingsShowStatusBarDesc: String,
        // About
        val aboutTitle: String,
        val aboutDescription: String,
        val aboutFeatures: String,
        val aboutTechStack: String,
        val aboutVersion: String,
        val aboutBuild: String,
        val aboutDeveloper: String,
        val aboutLicense: String,
        val aboutSource: String,
        val aboutFeature1: String,
        val aboutFeature2: String,
        val aboutFeature3: String,
        val aboutFeature4: String,
        val aboutFeature5: String,
        val aboutFeature6: String,
        val aboutFeature7: String,
        val aboutFeature8: String,
        val aboutFeature9: String,
        val aboutFeature10: String,
        val aboutFeature11: String,
        val aboutFeature12: String,
        val aboutFeature13: String,
        val aboutFeature14: String,
        val aboutFeature15: String,
        val aboutFeature16: String,
        val aboutFeature17: String,
        val aboutFeature18: String,
        // Errors
        val errorCreateFile: String,
        val errorCreateFolder: String,
        val errorLoadFile: String,
        val errorSaveFile: String,
        val errorInvalidLine: String,
        val errorRenameFailed: String,
        val errorDeleteFailed: String,
        val errorDuplicateFailed: String,
        // Common
        val commonOk: String,
        val commonFiles: String,
        val commonFolders: String,
        val commonSortByName: String,
        val commonSortBySize: String,
        val commonSortByModified: String,
        val commonShowHiddenFiles: String,
        val commonHideHiddenFiles: String,
        val commonNoResults: String,
        val commonMatchInFile: String,
        // v0.0.7 — new strings for cleaner UI
        val commonMenu: String,
        val commonMore: String,
        val commonLoading: String,
        val commonCancel: String,
        val commonRetry: String,
        val editorMore: String,
        val editorCaseSensitive: String,
        val editorRegex: String,
        val editorNoCommentSyntax: String,
        val editorFileTruncated: String,
        val editorFileTruncatedHint: String,
        val editorOpenFileFailed: String,
        val editorOpenFolderFailed: String,
        val settingsPreviewSection: String,
        val settingsPreviewDelay: String,
        val settingsAboutSection: String,
        val settingsAboutOpen: String,
        val settingsResetDefaults: String,
        val settingsResetConfirm: String,
        val aboutRateApp: String,
        val aboutShareApp: String,
        val aboutUpdates: String,
        val aboutNewVersion: String,
        // v0.0.9 — SUPER UPDATE: autocomplete + new editor toggles.
        val settingsAutocompleteDesc: String,
        val settingsShowWhitespace: String,
        val settingsShowWhitespaceDesc: String,
        val settingsShowIndentGuides: String,
        val settingsShowIndentGuidesDesc: String,
        val settingsShowBracketMatch: String,
        val settingsShowBracketMatchDesc: String,
        val settingsShowMinimap: String,
        val settingsShowMinimapDesc: String,
        val settingsHighlightCurrentLine: String,
        val settingsHighlightCurrentLineDesc: String,
        val settingsStickyHeader: String,
        val settingsStickyHeaderDesc: String,
        val settingsTrimTrailingWsOnSave: String,
        val settingsTrimTrailingWsOnSaveDesc: String,
        val settingsInsertFinalNewline: String,
        val settingsInsertFinalNewlineDesc: String,
        // v0.0.9 — bookmarks.
        val editorBookmarkToggle: String,
        val editorBookmarkNext: String,
        val editorBookmarkPrev: String,
        // v0.0.9 — text transforms.
        val editorTransformUpper: String,
        val editorTransformLower: String,
        val editorTransformTitle: String,
        val editorSortLinesAsc: String,
        val editorSortLinesDesc: String,
        val editorDedupeLines: String,
        val editorTrimWhitespace: String,
        val editorEncodeBase64: String,
        val editorDecodeBase64: String,
        val editorEncodeUrl: String,
        val editorDecodeUrl: String,
        val editorEncodeHtml: String,
        val editorDecodeHtml: String,
        val editorToUnixEol: String,
        val editorToWindowsEol: String,
        val editorIndent: String,
        val editorDedent: String,
        val editorTabsToSpaces: String,
        val editorSpacesToTabs: String,
        val editorNumberLines: String,
        val editorRemoveEmptyLines: String,
        val editorReverseLines: String,
        val editorToCamelCase: String,
        val editorToSnakeCase: String,
        val editorToKebabCase: String,
        val editorToConstantCase: String,
        val editorSlugify: String,
        val editorRot13: String,
        // v0.0.9 — Tools screen.
        val toolsTitle: String,
        val toolsSubtitle: String,
        val toolJsonFormat: String,
        val toolJsonMinify: String,
        val toolUuidGen: String,
        val toolLoremIpsum: String,
        val toolPasswordGen: String,
        val toolHashGen: String,
        val toolTimestampConv: String,
        val toolColorPicker: String,
        val toolRegexTester: String,
        val toolCronHelper: String,
        val toolJwtDecoder: String,
        val toolQrGenerator: String,
        val toolBase64: String,
        val toolUrlEncoder: String,
        val toolHtmlEncoder: String,
        val toolSlugGenerator: String,
        val toolTextDiff: String,
        val toolWordCount: String,
        val toolMarkdownPreview: String,
        val toolHexViewer: String,
        val toolExplainShell: String,
        val toolCheatSheet: String,
        val toolAboutTools: String,
        // v0.0.9 — Themes screen.
        val themesTitle: String,
        val themeViperDefault: String,
        val themeDracula: String,
        val themeMonokai: String,
        val themeSolarizedLight: String,
        val themeSolarizedDark: String,
        val themeGithubLight: String,
        val themeGithubDark: String,
        val themeOneDark: String,
        val themeMaterial: String,
        val themeNord: String,
        val themeGruvbox: String,
        val themeTokyoNight: String,
        val themeCatppuccin: String,
        // v0.0.9 — Snippets screen.
        val snippetsTitle: String,
        val snippetsSubtitle: String,
        val snippetsCustom: String,
        val snippetsBuiltin: String,
        val snippetsNew: String,
        val snippetsImport: String,
        val snippetsExport: String,
        // v0.0.9 — Symbol outline.
        val symbolOutlineTitle: String,
        val symbolOutlineEmpty: String,
        val symbolOutlineFunctions: String,
        val symbolOutlineClasses: String,
        val symbolOutlineImports: String,
        // v0.0.9 — TODO panel.
        val todoPanelTitle: String,
        val todoPanelEmpty: String,
        val todoPanelTodo: String,
        val todoPanelFixme: String,
        val todoPanelNote: String,
        // v0.0.9 — Welcome / onboarding.
        val welcomeTitle: String,
        val welcomeSubtitle: String,
        val welcomeGetStarted: String,
        val welcomePickFolder: String,
        val welcomeOpenFile: String,
        val welcomeExploreSettings: String,
        // v0.0.9 — Misc commonly-used strings.
        val copyToClipboard: String,
        val pasteFromClipboard: String,
        val selectAll: String,
        val selectLine: String,
        val selectWord: String,
        val formatDocument: String,
        val formatSelection: String,
        val foldAll: String,
        val unfoldAll: String,
        val pinTab: String,
        val unpinTab: String,
        val closeOthers: String,
        val closeAll: String,
        val reopenClosedTab: String,
        val splitEditor: String,
        val toggleSidebar: String,
        val goToDefinition: String,
        val findReferences: String,
        val renameSymbol: String,
        val formatOnSave: String,
        val organizeImports: String,
        val increaseFontSize: String,
        val decreaseFontSize: String,
        val resetFontSize: String,
        val addCursorAbove: String,
        val addCursorBelow: String,
        val selectNextOccurrence: String,
        val selectAllOccurrences: String,
        val reindentLines: String,
        val convertIndentation: String,
        val detectIndentation: String,
        val openTerminal: String,
        val openGit: String,
        val openOutline: String,
        val openSettings: String,
        val openSnippets: String,
        val openTemplates: String,
        val openThemes: String,
        val openTools: String,
        val openRecentFiles: String,
        val openKeyboardShortcuts: String,
        val openHelp: String,
        val openAboutMenu: String,
        val openCheckForUpdates: String,
        val openReportIssue: String,
        val openViewSource: String,
        val openChangelog: String,
        val openRoadmap: String,
        val openDocs: String,
    )

    private val ENGLISH = T(
        appName = "ViperCode",
        tagline = "The class of perfection",
        splashLoading = "Initializing workspace…",
        homeNoFolder = "No folder opened",
        homePickFolder = "Pick a folder to start coding",
        homeNewFile = "New file",
        homeNewFolder = "New folder",
        homeNewFileHere = "New file here",
        homeNewFolderHere = "New folder here",
        homeRefresh = "Refresh",
        homeOpenFolderSaf = "Open folder (SAF)",
        homeUseLocalWorkspace = "Use local workspace",
        homeSettings = "Settings",
        homeAbout = "About ViperCode",
        homeRecent = "Recent",
        homeNoRecent = "No recent files yet",
        homeClearRecent = "Clear recent list",
        homeUploadZip = "Upload ZIP to extract",
        homeSwitchFolder = "Switch folder",
        homeProjects = "Projects",
        homeNoProjects = "No projects extracted yet",
        homeFolderSectionWorkspace = "Workspace",
        homeFolderSectionProjects = "Extracted projects",
        homeFolderSectionRecent = "Recent folders",
        homeFolderSectionDevice = "Browse device",
        homeBrowseDevice = "Browse device storage",
        homeExtractingZip = "Extracting ZIP…",
        homeZipExtracted = "Extracted to %1\$s",
        homeZipExtractFailed = "Failed to extract ZIP",
        homeZipInvalid = "Selected file is not a valid ZIP archive",
        homeEmptyFolder = "This folder is empty",
        homeEmptyFolderHint = "Use the + button to create a new file or folder",
        homeCurrentFolder = "Current folder",
        dialogNewFileTitle = "New file",
        dialogNewFileHint = "e.g. main.kt",
        dialogNewFolderTitle = "New folder",
        dialogNewFolderHint = "e.g. src",
        dialogChooseAction = "Choose an action",
        dialogRename = "Rename",
        dialogDelete = "Delete",
        dialogDuplicate = "Duplicate",
        dialogCreate = "Create",
        dialogCancel = "Cancel",
        dialogConfirmDelete = "Delete \"%1\$s\"?",
        dialogUnsavedTitle = "Unsaved changes",
        dialogUnsavedBody = "Save before closing?",
        dialogSave = "Save",
        dialogDiscard = "Discard",
        dialogGoToLineTitle = "Go to line",
        dialogGoToLineHint = "Line number",
        dialogQuickOpenTitle = "Quick open",
        dialogSearchInFilesTitle = "Search in files",
        dialogSearchInFilesHint = "Search query",
        // v0.0.8 — new strings (English)
        dialogCommandPaletteTitle = "Command palette",
        dialogCommandPaletteHint = "Type a command name…",
        editorMoveLineUp = "Move line up",
        editorMoveLineDown = "Move line down",
        editorDuplicateLine = "Duplicate line",
        editorDeleteLine = "Delete line",
        editorCommandPalette = "Command palette",
        editorAutocompleteEnabled = "Autocomplete",
        settingsAutocomplete = "Code autocomplete",
        editorEmpty = "Open or create a file to start editing",
        editorSave = "Save",
        editorSaved = "Saved",
        editorSaveFailed = "Save failed",
        editorSearch = "Search",
        editorLivePreview = "Live preview",
        editorBack = "Back",
        editorCloseTab = "Close tab",
        editorReadOnly = "read-only",
        editorFind = "Find",
        editorReplace = "Replace",
        editorReplaceAll = "All",
        editorReplaceCurrent = "Replace current",
        editorNoMatchToReplace = "No match to replace",
        editorNoMatchesToReplace = "No matches to replace",
        editorPreviousMatch = "Previous match",
        editorNextMatch = "Next match",
        editorCloseSearch = "Close search",
        editorReplacedMatchN = "Replaced match %1\$d",
        editorReplacedNOccurrences = "Replaced %1\$d occurrence(s)",
        editorGoToLine = "Go to line",
        editorQuickOpen = "Quick open",
        editorSearchInFiles = "Search in files",
        editorWordWrap = "Word wrap",
        editorShowLineNumbers = "Show line numbers",
        editorAutoIndent = "Auto indent",
        editorShare = "Share file",
        editorShareFailed = "Share failed",
        editorCommentToggle = "Toggle comment",
        editorUndo = "Undo",
        editorRedo = "Redo",
        editorLines = "Lines",
        editorWords = "Words",
        editorChars = "Chars",
        editorCursor = "Ln %1\$d, Col %2\$d",
        editorSelected = "%1\$d selected",
        previewTitle = "Preview",
        previewSubtitle = "Live HTML/CSS/JS",
        previewEmpty = "Empty document",
        previewBackToEditor = "Back to editor",
        previewReload = "Reload preview",
        previewLiveToggle = "Live refresh",
        previewConsole = "Console",
        previewConsoleEmpty = "No console output",
        previewClearConsole = "Clear console",
        previewShare = "Share HTML",
        previewShareFailed = "Share failed",
        previewOpenExternal = "Open in browser",
        previewDesktopView = "Desktop view",
        previewMobileView = "Mobile view",
        previewMarkdown = "Markdown preview",
        previewNoPreview = "No preview available for this file type",
        settingsTitle = "Settings",
        settingsAppearance = "Appearance",
        settingsLanguage = "Language",
        settingsLanguageDesc = "App interface language",
        settingsTheme = "Theme",
        settingsThemeSystem = "System",
        settingsThemeDark = "Dark",
        settingsThemeLight = "Light",
        settingsDynamicColor = "Dynamic color (Android 12+)",
        settingsDynamicColorDesc = "Use the system palette if available",
        settingsEditor = "Editor",
        settingsFontSize = "Font size",
        settingsTabSize = "Tab size",
        settingsTabSizeValue = "%1\$d spaces",
        settingsWordWrap = "Word wrap",
        settingsWordWrapDesc = "Wrap long lines instead of horizontal scroll",
        settingsLineNumbers = "Show line numbers",
        settingsLineNumbersDesc = "Display the gutter column on the left",
        settingsAutoIndent = "Auto indent",
        settingsAutoIndentDesc = "Match the previous line's indentation",
        settingsAutoSave = "Auto save",
        settingsAutoSaveDesc = "Save dirty files after a short idle delay",
        settingsAutoSaveDelay = "Auto-save delay",
        settingsFontFamily = "Editor font family",
        settingsStorage = "Storage (offline)",
        settingsUseLocalWorkspace = "Use local workspace",
        settingsUseLocalWorkspaceDesc = "Create a default offline workspace inside the app's private storage so ViperCode works without picking a folder",
        settingsHiddenFiles = "Show hidden files",
        settingsHiddenFilesDesc = "Reveal files and folders starting with a dot",
        settingsAutoCloseBrackets = "Auto-close brackets",
        settingsAutoCloseBracketsDesc = "Auto-insert closing brackets and quotes",
        settingsShowStatusBar = "Show status bar",
        settingsShowStatusBarDesc = "Display line/word/char count at the bottom",
        aboutTitle = "About",
        aboutDescription = "A modern, performant code editor for Android. Built for developers who demand the class of perfection in every keystroke.",
        aboutFeatures = "Features",
        aboutTechStack = "Tech stack",
        aboutVersion = "Version",
        aboutBuild = "Build",
        aboutDeveloper = "Developer",
        aboutLicense = "License",
        aboutSource = "Source",
        aboutFeature1 = "Multi-language syntax highlighting (30+ languages)",
        aboutFeature2 = "Multi-tab editing with dirty-state tracking",
        aboutFeature3 = "Storage Access Framework integration",
        aboutFeature4 = "Material 3 dynamic theming (Android 12+)",
        aboutFeature5 = "Optimised for Android 7.1.1+ (API 25)",
        aboutFeature6 = "Word wrap, line numbers, auto-indent",
        aboutFeature7 = "Find & Replace with regex + case toggle",
        aboutFeature8 = "Live HTML/CSS/JS preview via WebView",
        aboutFeature9 = "Cursor position persistence across tab switches",
        aboutFeature10 = "Vietnamese language support",
        aboutFeature11 = "Multi-file workspace search",
        aboutFeature12 = "Quick open + Go-to-line",
        aboutFeature13 = "Hidden files toggle + sort options",
        aboutFeature14 = "Auto-refresh preview with debounce",
        aboutFeature15 = "Auto-close brackets & quotes",
        aboutFeature16 = "Live Markdown preview",
        aboutFeature17 = "JavaScript console overlay in preview",
        aboutFeature18 = "Recent files, share & comment toggle",
        errorCreateFile = "Could not create file",
        errorCreateFolder = "Could not create folder",
        errorLoadFile = "Could not load file",
        errorSaveFile = "Could not save file",
        errorInvalidLine = "Invalid line number",
        errorRenameFailed = "Rename failed",
        errorDeleteFailed = "Delete failed",
        errorDuplicateFailed = "Duplicate failed",
        commonOk = "OK",
        commonFiles = "files",
        commonFolders = "folders",
        commonSortByName = "Sort by name",
        commonSortBySize = "Sort by size",
        commonSortByModified = "Sort by modified",
        commonShowHiddenFiles = "Show hidden files",
        commonHideHiddenFiles = "Hide hidden files",
        commonNoResults = "No results",
        commonMatchInFile = "%1\$d match(es) in %2\$s",
        // v0.0.7 — new strings for cleaner UI
        commonMenu = "Menu",
        commonMore = "More",
        commonLoading = "Loading…",
        commonCancel = "Cancel",
        commonRetry = "Retry",
        editorMore = "More",
        editorCaseSensitive = "Match case",
        editorRegex = "Regex",
        editorNoCommentSyntax = "Comments not supported for this language",
        editorFileTruncated = "File truncated",
        editorFileTruncatedHint = "Files over 5 MB are read-only and truncated for performance",
        editorOpenFileFailed = "Failed to open file",
        editorOpenFolderFailed = "Failed to open folder",
        settingsPreviewSection = "Live preview",
        settingsPreviewDelay = "Preview auto-refresh delay",
        settingsAboutSection = "About",
        settingsAboutOpen = "About ViperCode",
        settingsResetDefaults = "Reset to defaults",
        settingsResetConfirm = "Reset all settings to their defaults?",
        aboutRateApp = "Rate on Play Store",
        aboutShareApp = "Share ViperCode",
        aboutUpdates = "Check for updates",
        aboutNewVersion = "A new version is available",
        // v0.0.9 — SUPER UPDATE (ENGLISH)
        settingsAutocompleteDesc = "Show a popup of keywords, snippets, and identifiers as you type",
        settingsShowWhitespace = "Show whitespace characters",
        settingsShowWhitespaceDesc = "Render spaces, tabs, and line endings as visible glyphs",
        settingsShowIndentGuides = "Show indent guides",
        settingsShowIndentGuidesDesc = "Draw vertical guides at each indent level",
        settingsShowBracketMatch = "Highlight matching bracket",
        settingsShowBracketMatchDesc = "When the caret is next to a bracket, highlight its pair",
        settingsShowMinimap = "Show minimap",
        settingsShowMinimapDesc = "Render a small overview of the whole file in the gutter",
        settingsHighlightCurrentLine = "Highlight current line",
        settingsHighlightCurrentLineDesc = "Apply a subtle background tint to the line the caret is on",
        settingsStickyHeader = "Sticky header",
        settingsStickyHeaderDesc = "Pin the current function/class header to the top while scrolling",
        settingsTrimTrailingWsOnSave = "Trim trailing whitespace on save",
        settingsTrimTrailingWsOnSaveDesc = "Strip trailing whitespace from each line before writing to disk",
        settingsInsertFinalNewline = "Insert final newline",
        settingsInsertFinalNewlineDesc = "Ensure the file ends with a single trailing newline",
        editorBookmarkToggle = "Toggle bookmark",
        editorBookmarkNext = "Next bookmark",
        editorBookmarkPrev = "Previous bookmark",
        editorTransformUpper = "UPPERCASE",
        editorTransformLower = "lowercase",
        editorTransformTitle = "Title Case",
        editorSortLinesAsc = "Sort lines A→Z",
        editorSortLinesDesc = "Sort lines Z→A",
        editorDedupeLines = "Remove duplicate lines",
        editorTrimWhitespace = "Trim trailing whitespace",
        editorEncodeBase64 = "Encode Base64",
        editorDecodeBase64 = "Decode Base64",
        editorEncodeUrl = "Encode URL",
        editorDecodeUrl = "Decode URL",
        editorEncodeHtml = "Escape HTML entities",
        editorDecodeHtml = "Unescape HTML entities",
        editorToUnixEol = "Convert to LF (Unix)",
        editorToWindowsEol = "Convert to CRLF (Windows)",
        editorIndent = "Indent selection",
        editorDedent = "Dedent selection",
        editorTabsToSpaces = "Tabs → spaces",
        editorSpacesToTabs = "Spaces → tabs",
        editorNumberLines = "Number lines",
        editorRemoveEmptyLines = "Remove empty lines",
        editorReverseLines = "Reverse line order",
        editorToCamelCase = "camelCase",
        editorToSnakeCase = "snake_case",
        editorToKebabCase = "kebab-case",
        editorToConstantCase = "CONSTANT_CASE",
        editorSlugify = "Slugify",
        editorRot13 = "ROT13",
        toolsTitle = "Tools",
        toolsSubtitle = "Built-in developer utilities",
        toolJsonFormat = "JSON formatter",
        toolJsonMinify = "JSON minifier",
        toolUuidGen = "UUID generator",
        toolLoremIpsum = "Lorem ipsum generator",
        toolPasswordGen = "Password generator",
        toolHashGen = "Hash generator (MD5/SHA1/SHA256)",
        toolTimestampConv = "Timestamp converter",
        toolColorPicker = "Color picker",
        toolRegexTester = "Regex tester",
        toolCronHelper = "Cron helper",
        toolJwtDecoder = "JWT decoder",
        toolQrGenerator = "QR code generator",
        toolBase64 = "Base64 encoder/decoder",
        toolUrlEncoder = "URL encoder/decoder",
        toolHtmlEncoder = "HTML entity encoder",
        toolSlugGenerator = "Slug generator",
        toolTextDiff = "Text diff",
        toolWordCount = "Word counter",
        toolMarkdownPreview = "Markdown preview",
        toolHexViewer = "Hex viewer",
        toolExplainShell = "Explain shell command",
        toolCheatSheet = "Cheat sheets",
        toolAboutTools = "Tools are offline — no data leaves your device",
        themesTitle = "Color themes",
        themeViperDefault = "ViperCode default",
        themeDracula = "Dracula",
        themeMonokai = "Monokai",
        themeSolarizedLight = "Solarized Light",
        themeSolarizedDark = "Solarized Dark",
        themeGithubLight = "GitHub Light",
        themeGithubDark = "GitHub Dark",
        themeOneDark = "One Dark",
        themeMaterial = "Material",
        themeNord = "Nord",
        themeGruvbox = "Gruvbox",
        themeTokyoNight = "Tokyo Night",
        themeCatppuccin = "Catppuccin",
        snippetsTitle = "Snippets",
        snippetsSubtitle = "Reusable code templates",
        snippetsCustom = "Custom snippets",
        snippetsBuiltin = "Built-in snippets",
        snippetsNew = "New snippet",
        snippetsImport = "Import",
        snippetsExport = "Export",
        symbolOutlineTitle = "Symbol outline",
        symbolOutlineEmpty = "No symbols found",
        symbolOutlineFunctions = "Functions",
        symbolOutlineClasses = "Classes & types",
        symbolOutlineImports = "Imports",
        todoPanelTitle = "TODO / FIXME",
        todoPanelEmpty = "No TODOs in this file",
        todoPanelTodo = "TODO",
        todoPanelFixme = "FIXME",
        todoPanelNote = "NOTE",
        welcomeTitle = "Welcome to ViperCode",
        welcomeSubtitle = "A modern code editor for Android — built for developers on the go",
        welcomeGetStarted = "Get started",
        welcomePickFolder = "Pick a folder to begin coding",
        welcomeOpenFile = "Open a file from your device",
        welcomeExploreSettings = "Explore settings & themes",
        copyToClipboard = "Copy to clipboard",
        pasteFromClipboard = "Paste from clipboard",
        selectAll = "Select all",
        selectLine = "Select line",
        selectWord = "Select word",
        formatDocument = "Format document",
        formatSelection = "Format selection",
        foldAll = "Fold all",
        unfoldAll = "Unfold all",
        pinTab = "Pin tab",
        unpinTab = "Unpin tab",
        closeOthers = "Close others",
        closeAll = "Close all",
        reopenClosedTab = "Reopen closed tab",
        splitEditor = "Split editor",
        toggleSidebar = "Toggle sidebar",
        goToDefinition = "Go to definition",
        findReferences = "Find all references",
        renameSymbol = "Rename symbol",
        formatOnSave = "Format on save",
        organizeImports = "Organize imports",
        increaseFontSize = "Increase font size",
        decreaseFontSize = "Decrease font size",
        resetFontSize = "Reset font size",
        addCursorAbove = "Add cursor above",
        addCursorBelow = "Add cursor below",
        selectNextOccurrence = "Select next occurrence",
        selectAllOccurrences = "Select all occurrences",
        reindentLines = "Reindent lines",
        convertIndentation = "Convert indentation",
        detectIndentation = "Detect indentation from file",
        openTerminal = "Open terminal",
        openGit = "Open Git panel",
        openOutline = "Open outline",
        openSettings = "Open settings",
        openSnippets = "Open snippets",
        openTemplates = "Open templates",
        openThemes = "Open themes",
        openTools = "Open tools",
        openRecentFiles = "Open recent files",
        openKeyboardShortcuts = "Keyboard shortcuts",
        openHelp = "Help",
        openAboutMenu = "About",
        openCheckForUpdates = "Check for updates",
        openReportIssue = "Report an issue",
        openViewSource = "View source on GitHub",
        openChangelog = "View changelog",
        openRoadmap = "View roadmap",
        openDocs = "View documentation",

    )

    private val VIETNAMESE = T(
        appName = "ViperCode",
        tagline = "Đẳng cấp hoàn hảo",
        splashLoading = "Đang khởi tạo không gian làm việc…",
        homeNoFolder = "Chưa mở thư mục nào",
        homePickFolder = "Chọn một thư mục để bắt đầu code",
        homeNewFile = "Tạo tệp mới",
        homeNewFolder = "Tạo thư mục mới",
        homeNewFileHere = "Tạo tệp tại đây",
        homeNewFolderHere = "Tạo thư mục tại đây",
        homeRefresh = "Làm mới",
        homeOpenFolderSaf = "Mở thư mục (SAF)",
        homeUseLocalWorkspace = "Dùng thư mục cục bộ",
        homeSettings = "Cài đặt",
        homeAbout = "Giới thiệu ViperCode",
        homeRecent = "Vừa mở",
        homeNoRecent = "Chưa có tệp nào vừa mở",
        homeClearRecent = "Xoá danh sách vừa mở",
        homeUploadZip = "Tải ZIP lên để giải nén",
        homeSwitchFolder = "Đổi thư mục",
        homeProjects = "Dự án",
        homeNoProjects = "Chưa có dự án nào được giải nén",
        homeFolderSectionWorkspace = "Workspace",
        homeFolderSectionProjects = "Dự án đã giải nén",
        homeFolderSectionRecent = "Thư mục gần đây",
        homeFolderSectionDevice = "Duyệt thiết bị",
        homeBrowseDevice = "Duyệt bộ nhớ thiết bị",
        homeExtractingZip = "Đang giải nén ZIP…",
        homeZipExtracted = "Đã giải nén vào %1\$s",
        homeZipExtractFailed = "Giải nén ZIP thất bại",
        homeZipInvalid = "Tệp được chọn không phải là ZIP hợp lệ",
        homeEmptyFolder = "Thư mục này trống",
        homeEmptyFolderHint = "Dùng nút + để tạo tệp hoặc thư mục mới",
        homeCurrentFolder = "Thư mục hiện tại",
        dialogNewFileTitle = "Tệp mới",
        dialogNewFileHint = "vd: main.kt",
        dialogNewFolderTitle = "Thư mục mới",
        dialogNewFolderHint = "vd: src",
        dialogChooseAction = "Chọn hành động",
        dialogRename = "Đổi tên",
        dialogDelete = "Xoá",
        dialogDuplicate = "Nhân bản",
        dialogCreate = "Tạo",
        dialogCancel = "Huỷ",
        dialogConfirmDelete = "Xoá \"%1\$s\"?",
        dialogUnsavedTitle = "Chưa lưu thay đổi",
        dialogUnsavedBody = "Lưu trước khi đóng?",
        dialogSave = "Lưu",
        dialogDiscard = "Bỏ qua",
        dialogGoToLineTitle = "Nhảy tới dòng",
        dialogGoToLineHint = "Số dòng",
        dialogQuickOpenTitle = "Mở nhanh",
        dialogSearchInFilesTitle = "Tìm trong tệp",
        dialogSearchInFilesHint = "Nội dung tìm",
        // v0.0.8 — new strings (Vietnamese)
        dialogCommandPaletteTitle = "Bảng lệnh",
        dialogCommandPaletteHint = "Gõ tên lệnh…",
        editorMoveLineUp = "Đẩy dòng lên",
        editorMoveLineDown = "Đẩy dòng xuống",
        editorDuplicateLine = "Nhân đôi dòng",
        editorDeleteLine = "Xoá dòng",
        editorCommandPalette = "Bảng lệnh",
        editorAutocompleteEnabled = "Gợi ý mã",
        settingsAutocomplete = "Gợi ý mã tự động",
        editorEmpty = "Mở hoặc tạo tệp để bắt đầu soạn thảo",
        editorSave = "Lưu",
        editorSaved = "Đã lưu",
        editorSaveFailed = "Lưu thất bại",
        editorSearch = "Tìm",
        editorLivePreview = "Xem trước trực tiếp",
        editorBack = "Quay lại",
        editorCloseTab = "Đóng tab",
        editorReadOnly = "chỉ đọc",
        editorFind = "Tìm",
        editorReplace = "Thay thế",
        editorReplaceAll = "Tất cả",
        editorReplaceCurrent = "Thay kết quả này",
        editorNoMatchToReplace = "Không có kết quả để thay",
        editorNoMatchesToReplace = "Không có kết quả nào để thay",
        editorPreviousMatch = "Kết quả trước",
        editorNextMatch = "Kết quả sau",
        editorCloseSearch = "Đóng ô tìm kiếm",
        editorReplacedMatchN = "Đã thay kết quả %1\$d",
        editorReplacedNOccurrences = "Đã thay %1\$d lần xuất hiện",
        editorGoToLine = "Nhảy tới dòng",
        editorQuickOpen = "Mở nhanh",
        editorSearchInFiles = "Tìm trong tệp",
        editorWordWrap = "Tự động xuống dòng",
        editorShowLineNumbers = "Hiện số dòng",
        editorAutoIndent = "Tự động thụt lề",
        editorShare = "Chia sẻ tệp",
        editorShareFailed = "Chia sẻ thất bại",
        editorCommentToggle = "Bật/tắt ghi chú",
        editorUndo = "Hoàn tác",
        editorRedo = "Làm lại",
        editorLines = "Dòng",
        editorWords = "Từ",
        editorChars = "Ký tự",
        editorCursor = "Dòng %1\$d, Cột %2\$d",
        editorSelected = "Đã chọn %1\$d",
        previewTitle = "Xem trước",
        previewSubtitle = "HTML/CSS/JS trực tiếp",
        previewEmpty = "Tài liệu rỗng",
        previewBackToEditor = "Quay lại trình soạn thảo",
        previewReload = "Tải lại xem trước",
        previewLiveToggle = "Tự làm mới",
        previewConsole = "Bảng điều khiển",
        previewConsoleEmpty = "Chưa có log nào",
        previewClearConsole = "Xoá log",
        previewShare = "Chia sẻ HTML",
        previewShareFailed = "Chia sẻ thất bại",
        previewOpenExternal = "Mở trong trình duyệt",
        previewDesktopView = "Giao diện máy tính",
        previewMobileView = "Giao diện di động",
        previewMarkdown = "Xem trước Markdown",
        previewNoPreview = "Không có xem trước cho loại tệp này",
        settingsTitle = "Cài đặt",
        settingsAppearance = "Giao diện",
        settingsLanguage = "Ngôn ngữ",
        settingsLanguageDesc = "Ngôn ngữ giao diện ứng dụng",
        settingsTheme = "Chủ đề",
        settingsThemeSystem = "Hệ thống",
        settingsThemeDark = "Tối",
        settingsThemeLight = "Sáng",
        settingsDynamicColor = "Màu động (Android 12+)",
        settingsDynamicColorDesc = "Dùng bảng màu hệ thống nếu có",
        settingsEditor = "Trình soạn thảo",
        settingsFontSize = "Cỡ chữ",
        settingsTabSize = "Độ rộng Tab",
        settingsTabSizeValue = "%1\$d khoảng trắng",
        settingsWordWrap = "Tự xuống dòng",
        settingsWordWrapDesc = "Cuốn dòng dài thay vì cuộn ngang",
        settingsLineNumbers = "Hiện số dòng",
        settingsLineNumbersDesc = "Hiển thị cột số dòng bên trái",
        settingsAutoIndent = "Tự thụt lề",
        settingsAutoIndentDesc = "Theo thụt lề của dòng trước đó",
        settingsAutoSave = "Tự động lưu",
        settingsAutoSaveDesc = "Lưu tệp chưa lưu sau một khoảng nghỉ",
        settingsAutoSaveDelay = "Độ trễ tự lưu",
        settingsFontFamily = "Font trình soạn thảo",
        settingsStorage = "Lưu trữ (ngoại tuyến)",
        settingsUseLocalWorkspace = "Dùng thư mục cục bộ",
        settingsUseLocalWorkspaceDesc = "Tạo một thư mục mặc định trong bộ nhớ riêng của ứng dụng để ViperCode dùng được ngay mà không cần chọn thư mục",
        settingsHiddenFiles = "Hiện tệp ẩn",
        settingsHiddenFilesDesc = "Hiển thị tệp và thư mục bắt đầu bằng dấu chấm",
        settingsAutoCloseBrackets = "Tự đóng ngoặc",
        settingsAutoCloseBracketsDesc = "Tự chèn ngoặc đóng và dấu ngoặc kép",
        settingsShowStatusBar = "Hiện thanh trạng thái",
        settingsShowStatusBarDesc = "Hiển thị số dòng/từ/ký tự ở dưới cùng",
        aboutTitle = "Giới thiệu",
        aboutDescription = "Trình soạn thảo code Android hiện đại, mượt mà. Dành cho những lập trình viên đòi hỏi đẳng cấp hoàn hảo trong từng phím gõ.",
        aboutFeatures = "Tính năng",
        aboutTechStack = "Tech stack",
        aboutVersion = "Phiên bản",
        aboutBuild = "Build",
        aboutDeveloper = "Tác giả",
        aboutLicense = "Giấy phép",
        aboutSource = "Mã nguồn",
        aboutFeature1 = "Tô màu cú pháp 30+ ngôn ngữ lập trình",
        aboutFeature2 = "Mở nhiều tab cùng lúc, theo dõi trạng thái chưa lưu",
        aboutFeature3 = "Tích hợp Storage Access Framework",
        aboutFeature4 = "Tô màu động Material 3 (Android 12+)",
        aboutFeature5 = "Tối ưu cho Android 7.1.1+ (API 25)",
        aboutFeature6 = "Tự xuống dòng, số dòng, tự thụt lề",
        aboutFeature7 = "Tìm & Thay thế với regex + phân biệt hoa/thường",
        aboutFeature8 = "Xem trước HTML/CSS/JS trực tiếp qua WebView",
        aboutFeature9 = "Lưu vị trí con trỏ khi chuyển tab",
        aboutFeature10 = "Hỗ trợ tiếng Việt",
        aboutFeature11 = "Tìm kiếm toàn bộ workspace",
        aboutFeature12 = "Mở nhanh + Nhảy tới dòng",
        aboutFeature13 = "Bật tệp ẩn + tuỳ chọn sắp xếp",
        aboutFeature14 = "Tự làm mới xem trước có debounce",
        aboutFeature15 = "Tự đóng ngoặc & dấu ngoặc kép",
        aboutFeature16 = "Xem trước Markdown trực tiếp",
        aboutFeature17 = "Bảng console JavaScript trong xem trước",
        aboutFeature18 = "Tệp vừa mở, chia sẻ & bật/tắt ghi chú",
        errorCreateFile = "Không tạo được tệp",
        errorCreateFolder = "Không tạo được thư mục",
        errorLoadFile = "Không đọc được tệp",
        errorSaveFile = "Không lưu được tệp",
        errorInvalidLine = "Số dòng không hợp lệ",
        errorRenameFailed = "Đổi tên thất bại",
        errorDeleteFailed = "Xoá thất bại",
        errorDuplicateFailed = "Nhân bản thất bại",
        commonOk = "OK",
        commonFiles = "tệp",
        commonFolders = "thư mục",
        commonSortByName = "Sắp theo tên",
        commonSortBySize = "Sắp theo kích thước",
        commonSortByModified = "Sắp theo thời gian",
        commonShowHiddenFiles = "Hiện tệp ẩn",
        commonHideHiddenFiles = "Ẩn tệp ẩn",
        commonNoResults = "Không có kết quả",
        commonMatchInFile = "%1\$d kết quả trong %2\$s",
        // v0.0.7 — new strings for cleaner UI
        commonMenu = "Menu",
        commonMore = "Thêm",
        commonLoading = "Đang tải…",
        commonCancel = "Huỷ",
        commonRetry = "Thử lại",
        editorMore = "Thêm",
        editorCaseSensitive = "Phân biệt hoa/thường",
        editorRegex = "Regex",
        editorNoCommentSyntax = "Ngôn ngữ này không hỗ trợ ghi chú dòng",
        editorFileTruncated = "Tệp bị cắt ngắn",
        editorFileTruncatedHint = "Tệp trên 5 MB được mở chỉ đọc và cắt ngắn để tránh tràn RAM",
        editorOpenFileFailed = "Không mở được tệp",
        editorOpenFolderFailed = "Không mở được thư mục",
        settingsPreviewSection = "Xem trước trực tiếp",
        settingsPreviewDelay = "Độ trễ tự làm mới xem trước",
        settingsAboutSection = "Giới thiệu",
        settingsAboutOpen = "Giới thiệu ViperCode",
        settingsResetDefaults = "Đặt lại mặc định",
        settingsResetConfirm = "Đặt lại toàn bộ cài đặt về mặc định?",
        aboutRateApp = "Đánh giá trên Play Store",
        aboutShareApp = "Chia sẻ ViperCode",
        aboutUpdates = "Kiểm tra cập nhật",
        aboutNewVersion = "Có phiên bản mới",
        // v0.0.9 — SUPER UPDATE (VIETNAMESE)
        settingsAutocompleteDesc = "Hiện popup gợi ý từ khoá, snippet và identifier khi gõ",
        settingsShowWhitespace = "Hiện ký tự whitespace",
        settingsShowWhitespaceDesc = "Hiển thị dấu cách, tab và kết thúc dòng dưới dạng ký tự nhìn thấy",
        settingsShowIndentGuides = "Hiện đường dẫn thụt lề",
        settingsShowIndentGuidesDesc = "Vẽ đường dọc tại mỗi mức thụt lề",
        settingsShowBracketMatch = "Tô sáng ngoặc khớp",
        settingsShowBracketMatchDesc = "Khi con trỏ cạnh một ngoặc, tô sáng ngoặc khớp",
        settingsShowMinimap = "Hiện minimap",
        settingsShowMinimapDesc = "Hiển thị sơ đồ tổng quan của cả tệp ở cột bên trái",
        settingsHighlightCurrentLine = "Tô sáng dòng hiện tại",
        settingsHighlightCurrentLineDesc = "Tô nền nhẹ dòng chứa con trỏ",
        settingsStickyHeader = "Sticky header",
        settingsStickyHeaderDesc = "Ghim tiêu đề hàm/lớp hiện tại lên đầu khi cuộn",
        settingsTrimTrailingWsOnSave = "Xoá whitespace cuối dòng khi lưu",
        settingsTrimTrailingWsOnSaveDesc = "Xoá whitespace ở cuối mỗi dòng trước khi ghi ra tệp",
        settingsInsertFinalNewline = "Chèn dòng trống cuối tệp",
        settingsInsertFinalNewlineDesc = "Đảm bảo tệp kết thúc bằng một dòng trống",
        editorBookmarkToggle = "Bật/tắt bookmark",
        editorBookmarkNext = "Bookmark tiếp theo",
        editorBookmarkPrev = "Bookmark trước đó",
        editorTransformUpper = "IN HOA",
        editorTransformLower = "in thường",
        editorTransformTitle = "Viết Hoa Đầu",
        editorSortLinesAsc = "Sắp dòng A→Z",
        editorSortLinesDesc = "Sắp dòng Z→A",
        editorDedupeLines = "Xoá dòng trùng lặp",
        editorTrimWhitespace = "Cắt whitespace cuối dòng",
        editorEncodeBase64 = "Mã hoá Base64",
        editorDecodeBase64 = "Giải mã Base64",
        editorEncodeUrl = "Mã hoá URL",
        editorDecodeUrl = "Giải mã URL",
        editorEncodeHtml = "Mã hoá thực thể HTML",
        editorDecodeHtml = "Giải mã thực thể HTML",
        editorToUnixEol = "Chuyển sang LF (Unix)",
        editorToWindowsEol = "Chuyển sang CRLF (Windows)",
        editorIndent = "Thụt lề đoạn chọn",
        editorDedent = "Bớt thụt lề",
        editorTabsToSpaces = "Tab → dấu cách",
        editorSpacesToTabs = "Dấu cách → tab",
        editorNumberLines = "Đánh số dòng",
        editorRemoveEmptyLines = "Xoá dòng trống",
        editorReverseLines = "Đảo thứ tự dòng",
        editorToCamelCase = "camelCase",
        editorToSnakeCase = "snake_case",
        editorToKebabCase = "kebab-case",
        editorToConstantCase = "CONSTANT_CASE",
        editorSlugify = "Slugify",
        editorRot13 = "ROT13",
        toolsTitle = "Công cụ",
        toolsSubtitle = "Tiện ích dành cho lập trình viên",
        toolJsonFormat = "Định dạng JSON",
        toolJsonMinify = "Rút gọn JSON",
        toolUuidGen = "Tạo UUID",
        toolLoremIpsum = "Tạo Lorem ipsum",
        toolPasswordGen = "Tạo mật khẩu",
        toolHashGen = "Tạo hash (MD5/SHA1/SHA256)",
        toolTimestampConv = "Chuyển đổi timestamp",
        toolColorPicker = "Bảng chọn màu",
        toolRegexTester = "Thử regex",
        toolCronHelper = "Hỗ trợ Cron",
        toolJwtDecoder = "Giải mã JWT",
        toolQrGenerator = "Tạo mã QR",
        toolBase64 = "Mã hoá/giải mã Base64",
        toolUrlEncoder = "Mã hoá/giải mã URL",
        toolHtmlEncoder = "Mã hoá thực thể HTML",
        toolSlugGenerator = "Tạo slug",
        toolTextDiff = "So sánh văn bản",
        toolWordCount = "Đếm từ",
        toolMarkdownPreview = "Xem trước Markdown",
        toolHexViewer = "Trình xem hex",
        toolExplainShell = "Giải thích lệnh shell",
        toolCheatSheet = "Tổng hợp mẹo",
        toolAboutTools = "Công cụ hoạt động ngoại tuyến — không gửi dữ liệu đi",
        themesTitle = "Chủ đề màu",
        themeViperDefault = "Mặc định ViperCode",
        themeDracula = "Dracula",
        themeMonokai = "Monokai",
        themeSolarizedLight = "Solarized Sáng",
        themeSolarizedDark = "Solarized Tối",
        themeGithubLight = "GitHub Sáng",
        themeGithubDark = "GitHub Tối",
        themeOneDark = "One Dark",
        themeMaterial = "Material",
        themeNord = "Nord",
        themeGruvbox = "Gruvbox",
        themeTokyoNight = "Tokyo Night",
        themeCatppuccin = "Catppuccin",
        snippetsTitle = "Snippet",
        snippetsSubtitle = "Mẫu code tái sử dụng",
        snippetsCustom = "Snippet tuỳ chỉnh",
        snippetsBuiltin = "Snippet có sẵn",
        snippetsNew = "Snippet mới",
        snippetsImport = "Nhập",
        snippetsExport = "Xuất",
        symbolOutlineTitle = "Sơ đồ ký hiệu",
        symbolOutlineEmpty = "Không tìm thấy ký hiệu",
        symbolOutlineFunctions = "Hàm",
        symbolOutlineClasses = "Lớp & kiểu",
        symbolOutlineImports = "Imports",
        todoPanelTitle = "TODO / FIXME",
        todoPanelEmpty = "Không có TODO nào trong tệp",
        todoPanelTodo = "TODO",
        todoPanelFixme = "FIXME",
        todoPanelNote = "NOTE",
        welcomeTitle = "Chào mừng đến ViperCode",
        welcomeSubtitle = "Trình soạn thảo code hiện đại cho Android — dành cho lập trình viên hay di chuyển",
        welcomeGetStarted = "Bắt đầu",
        welcomePickFolder = "Chọn thư mục để bắt đầu code",
        welcomeOpenFile = "Mở tệp từ thiết bị",
        welcomeExploreSettings = "Khám phá cài đặt & chủ đề",
        copyToClipboard = "Chép vào clipboard",
        pasteFromClipboard = "Dán từ clipboard",
        selectAll = "Chọn tất cả",
        selectLine = "Chọn dòng",
        selectWord = "Chọn từ",
        formatDocument = "Định dạng tài liệu",
        formatSelection = "Định dạng đoạn chọn",
        foldAll = "Thu gọn tất cả",
        unfoldAll = "Mở rộng tất cả",
        pinTab = "Ghim tab",
        unpinTab = "Bỏ ghim tab",
        closeOthers = "Đóng các tab khác",
        closeAll = "Đóng tất cả",
        reopenClosedTab = "Mở lại tab đã đóng",
        splitEditor = "Chia trình soạn thảo",
        toggleSidebar = "Bật/tắt thanh bên",
        goToDefinition = "Tới định nghĩa",
        findReferences = "Tìm mọi tham chiếu",
        renameSymbol = "Đổi tên ký hiệu",
        formatOnSave = "Định dạng khi lưu",
        organizeImports = "Sắp xếp imports",
        increaseFontSize = "Tăng cỡ chữ",
        decreaseFontSize = "Giảm cỡ chữ",
        resetFontSize = "Đặt lại cỡ chữ",
        addCursorAbove = "Thêm con trỏ phía trên",
        addCursorBelow = "Thêm con trỏ phía dưới",
        selectNextOccurrence = "Chọn lần xuất hiện kế tiếp",
        selectAllOccurrences = "Chọn tất cả lần xuất hiện",
        reindentLines = "Thụt lề lại",
        convertIndentation = "Đổi kiểu thụt lề",
        detectIndentation = "Phát hiện thụt lề từ tệp",
        openTerminal = "Mở terminal",
        openGit = "Mở bảng Git",
        openOutline = "Mở sơ đồ",
        openSettings = "Mở cài đặt",
        openSnippets = "Mở snippets",
        openTemplates = "Mở templates",
        openThemes = "Mở chủ đề",
        openTools = "Mở công cụ",
        openRecentFiles = "Mở tệp gần đây",
        openKeyboardShortcuts = "Phím tắt",
        openHelp = "Trợ giúp",
        openAboutMenu = "Giới thiệu",
        openCheckForUpdates = "Kiểm tra cập nhật",
        openReportIssue = "Báo lỗi",
        openViewSource = "Xem mã nguồn trên GitHub",
        openChangelog = "Xem changelog",
        openRoadmap = "Xem roadmap",
        openDocs = "Xem tài liệu",

    )

    private val STRINGS: Map<Language, T> = mapOf(
        Language.ENGLISH to ENGLISH,
        Language.VIETNAMESE to VIETNAMESE,
    )

    private val _active = MutableStateFlow(Language.ENGLISH)
    val active: StateFlow<Language> = _active

    /** Returns the current catalogue. Compose callers should observe [active] first. */
    fun get(): T = STRINGS[_active.value] ?: ENGLISH

    /** Switches the active language at runtime. */
    fun setLanguage(lang: Language) {
        _active.value = lang
    }

    /** Resolves a [SettingsRepository.LanguageMode] pref to a [Language]. */
    fun applyMode(mode: SettingsRepository.LanguageMode) {
        _active.value = when (mode) {
            SettingsRepository.LanguageMode.SYSTEM -> {
                val lang = java.util.Locale.getDefault().language
                if (lang == "vi") Language.VIETNAMESE else Language.ENGLISH
            }
            SettingsRepository.LanguageMode.ENGLISH -> Language.ENGLISH
            SettingsRepository.LanguageMode.VIETNAMESE -> Language.VIETNAMESE
        }
    }
}
