package com.vipercode.ide.util

import com.vipercode.ide.data.prefs.SettingsRepository
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow

/**
 * Centralised, in-memory i18n layer for ViperCode.
 *
 * Added in v0.0.4 — the app ships with two languages: English (default)
 * and Vietnamese (Tiếng Việt). All UI strings go through [Strings.get]
 * so a single preference flip re-renders the whole app in the chosen
 * language without an Activity restart.
 *
 * The active language is published via a [StateFlow] so any composable
 * calling [Strings.get] inside a `collectAsState`-driven read will
 * recompose when the language changes.
 *
 * v0.0.4 keeps the implementation dependency-free (no Android resource
 * system, no ICU) so the runtime cost is a hashmap lookup. Adding a new
 * language is a one-step change: append a [Language] variant, fill in
 * the [STRINGS] map, and the rest of the app picks it up automatically.
 */
object Strings {

    enum class Language(val displayName: String, val nativeName: String) {
        ENGLISH("English", "English"),
        VIETNAMESE("Tiếng Việt", "Tiếng Việt"),
    }

    /**
     * The full string catalogue. Every key the app uses lives here so we
     * have a single source of truth — adding a new string is one entry
     * per language and the compiler will surface any missing key at the
     * call site (because [T] is a typed property, not a string lookup).
     */
    data class T(
        // App
        val appName: String,
        val tagline: String,
        // Splash
        val splashLoading: String,
        // Home
        val homeNoFolder: String,
        val homePickFolder: String,
        val homeNewFile: String,
        val homeNewFolder: String,
        val homeNewFileHere: String,
        val homeNewFolderHere: String,
        val homeRefresh: String,
        val homeOpenFolderSaf: String,
        val homeUseLocalWorkspace: String,
        val homeSettings: String,
        val homeAbout: String,
        val homeRecent: String,
        val homeNoRecent: String,
        val homeClearRecent: String,
        val homeUploadZip: String,
        val homeSwitchFolder: String,
        val homeProjects: String,
        val homeNoProjects: String,
        val homeFolderSectionWorkspace: String,
        val homeFolderSectionProjects: String,
        val homeFolderSectionRecent: String,
        val homeFolderSectionDevice: String,
        val homeBrowseDevice: String,
        val homeExtractingZip: String,
        val homeZipExtracted: String,
        val homeZipExtractFailed: String,
        val homeZipInvalid: String,
        val homeEmptyFolder: String,
        val homeEmptyFolderHint: String,
        val homeCurrentFolder: String,
        // Dialogs
        val dialogNewFileTitle: String,
        val dialogNewFileHint: String,
        val dialogNewFolderTitle: String,
        val dialogNewFolderHint: String,
        val dialogChooseAction: String,
        val dialogRename: String,
        val dialogDelete: String,
        val dialogDuplicate: String,
        val dialogCreate: String,
        val dialogCancel: String,
        val dialogConfirmDelete: String,
        val dialogUnsavedTitle: String,
        val dialogUnsavedBody: String,
        val dialogSave: String,
        val dialogDiscard: String,
        val dialogGoToLineTitle: String,
        val dialogGoToLineHint: String,
        val dialogQuickOpenTitle: String,
        val dialogSearchInFilesTitle: String,
        val dialogSearchInFilesHint: String,
        // Editor
        val editorEmpty: String,
        val editorSave: String,
        val editorSaved: String,
        val editorSaveFailed: String,
        val editorSearch: String,
        val editorLivePreview: String,
        val editorBack: String,
        val editorCloseTab: String,
        val editorReadOnly: String,
        val editorFind: String,
        val editorReplace: String,
        val editorReplaceAll: String,
        val editorReplaceCurrent: String,
        val editorNoMatchToReplace: String,
        val editorNoMatchesToReplace: String,
        val editorPreviousMatch: String,
        val editorNextMatch: String,
        val editorCloseSearch: String,
        val editorReplacedMatchN: String,
        val editorReplacedNOccurrences: String,
        val editorGoToLine: String,
        val editorQuickOpen: String,
        val editorSearchInFiles: String,
        val editorWordWrap: String,
        val editorShowLineNumbers: String,
        val editorAutoIndent: String,
        val editorShare: String,
        val editorShareFailed: String,
        val editorCommentToggle: String,
        val editorUndo: String,
        val editorRedo: String,
        val editorLines: String,
        val editorWords: String,
        val editorChars: String,
        val editorCursor: String,
        val editorSelected: String,
        // Preview
        val previewTitle: String,
        val previewSubtitle: String,
        val previewEmpty: String,
        val previewBackToEditor: String,
        val previewReload: String,
        val previewLiveToggle: String,
        val previewConsole: String,
        val previewConsoleEmpty: String,
        val previewClearConsole: String,
        val previewShare: String,
        val previewShareFailed: String,
        val previewOpenExternal: String,
        val previewDesktopView: String,
        val previewMobileView: String,
        val previewMarkdown: String,
        val previewNoPreview: String,
        // Settings
        val settingsTitle: String,
        val settingsAppearance: String,
        val settingsLanguage: String,
        val settingsLanguageDesc: String,
        val settingsTheme: String,
        val settingsThemeSystem: String,
        val settingsThemeDark: String,
        val settingsThemeLight: String,
        val settingsDynamicColor: String,
        val settingsDynamicColorDesc: String,
        val settingsEditor: String,
        val settingsFontSize: String,
        val settingsTabSize: String,
        val settingsTabSizeValue: String,
        val settingsWordWrap: String,
        val settingsWordWrapDesc: String,
        val settingsLineNumbers: String,
        val settingsLineNumbersDesc: String,
        val settingsAutoIndent: String,
        val settingsAutoIndentDesc: String,
        val settingsAutoSave: String,
        val settingsAutoSaveDesc: String,
        val settingsAutoSaveDelay: String,
        val settingsFontFamily: String,
        val settingsStorage: String,
        val settingsUseLocalWorkspace: String,
        val settingsUseLocalWorkspaceDesc: String,
        val settingsHiddenFiles: String,
        val settingsHiddenFilesDesc: String,
        val settingsAutoCloseBrackets: String,
        val settingsAutoCloseBracketsDesc: String,
        val settingsShowStatusBar: String,
        val settingsShowStatusBarDesc: String,
        // About
        val aboutTitle: String,
        val aboutDescription: String,
        val aboutFeatures: String,
        val aboutTechStack: String,
        val aboutVersion: String,
        val aboutBuild: String,
        val aboutDeveloper: String,
        val aboutLicense: String,
        val aboutSource: String,
        val aboutFeature1: String,
        val aboutFeature2: String,
        val aboutFeature3: String,
        val aboutFeature4: String,
        val aboutFeature5: String,
        val aboutFeature6: String,
        val aboutFeature7: String,
        val aboutFeature8: String,
        val aboutFeature9: String,
        val aboutFeature10: String,
        val aboutFeature11: String,
        val aboutFeature12: String,
        val aboutFeature13: String,
        val aboutFeature14: String,
        val aboutFeature15: String,
        val aboutFeature16: String,
        val aboutFeature17: String,
        val aboutFeature18: String,
        // Errors
        val errorCreateFile: String,
        val errorCreateFolder: String,
        val errorLoadFile: String,
        val errorSaveFile: String,
        val errorInvalidLine: String,
        val errorRenameFailed: String,
        val errorDeleteFailed: String,
        val errorDuplicateFailed: String,
        // Common
        val commonOk: String,
        val commonFiles: String,
        val commonFolders: String,
        val commonSortByName: String,
        val commonSortBySize: String,
        val commonSortByModified: String,
        val commonShowHiddenFiles: String,
        val commonHideHiddenFiles: String,
        val commonNoResults: String,
        val commonMatchInFile: String,
    )

    private val ENGLISH = T(
        appName = "ViperCode",
        tagline = "The class of perfection",
        splashLoading = "Initializing workspace…",
        homeNoFolder = "No folder opened",
        homePickFolder = "Pick a folder to start coding",
        homeNewFile = "New file",
        homeNewFolder = "New folder",
        homeNewFileHere = "New file here",
        homeNewFolderHere = "New folder here",
        homeRefresh = "Refresh",
        homeOpenFolderSaf = "Open folder (SAF)",
        homeUseLocalWorkspace = "Use local workspace",
        homeSettings = "Settings",
        homeAbout = "About ViperCode",
        homeRecent = "Recent",
        homeNoRecent = "No recent files yet",
        homeClearRecent = "Clear recent list",
        homeUploadZip = "Upload ZIP to extract",
        homeSwitchFolder = "Switch folder",
        homeProjects = "Projects",
        homeNoProjects = "No projects extracted yet",
        homeFolderSectionWorkspace = "Workspace",
        homeFolderSectionProjects = "Extracted projects",
        homeFolderSectionRecent = "Recent folders",
        homeFolderSectionDevice = "Browse device",
        homeBrowseDevice = "Browse device storage",
        homeExtractingZip = "Extracting ZIP…",
        homeZipExtracted = "Extracted to %1\$s",
        homeZipExtractFailed = "Failed to extract ZIP",
        homeZipInvalid = "Selected file is not a valid ZIP archive",
        homeEmptyFolder = "This folder is empty",
        homeEmptyFolderHint = "Use the + button to create a new file or folder",
        homeCurrentFolder = "Current folder",
        dialogNewFileTitle = "New file",
        dialogNewFileHint = "e.g. main.kt",
        dialogNewFolderTitle = "New folder",
        dialogNewFolderHint = "e.g. src",
        dialogChooseAction = "Choose an action",
        dialogRename = "Rename",
        dialogDelete = "Delete",
        dialogDuplicate = "Duplicate",
        dialogCreate = "Create",
        dialogCancel = "Cancel",
        dialogConfirmDelete = "Delete \"%1\$s\"?",
        dialogUnsavedTitle = "Unsaved changes",
        dialogUnsavedBody = "Save before closing?",
        dialogSave = "Save",
        dialogDiscard = "Discard",
        dialogGoToLineTitle = "Go to line",
        dialogGoToLineHint = "Line number",
        dialogQuickOpenTitle = "Quick open",
        dialogSearchInFilesTitle = "Search in files",
        dialogSearchInFilesHint = "Search query",
        editorEmpty = "Open or create a file to start editing",
        editorSave = "Save",
        editorSaved = "Saved",
        editorSaveFailed = "Save failed",
        editorSearch = "Search",
        editorLivePreview = "Live preview",
        editorBack = "Back",
        editorCloseTab = "Close tab",
        editorReadOnly = "read-only",
        editorFind = "Find",
        editorReplace = "Replace",
        editorReplaceAll = "All",
        editorReplaceCurrent = "Replace current",
        editorNoMatchToReplace = "No match to replace",
        editorNoMatchesToReplace = "No matches to replace",
        editorPreviousMatch = "Previous match",
        editorNextMatch = "Next match",
        editorCloseSearch = "Close search",
        editorReplacedMatchN = "Replaced match %1\$d",
        editorReplacedNOccurrences = "Replaced %1\$d occurrence(s)",
        editorGoToLine = "Go to line",
        editorQuickOpen = "Quick open",
        editorSearchInFiles = "Search in files",
        editorWordWrap = "Word wrap",
        editorShowLineNumbers = "Show line numbers",
        editorAutoIndent = "Auto indent",
        editorShare = "Share file",
        editorShareFailed = "Share failed",
        editorCommentToggle = "Toggle comment",
        editorUndo = "Undo",
        editorRedo = "Redo",
        editorLines = "Lines",
        editorWords = "Words",
        editorChars = "Chars",
        editorCursor = "Ln %1\$d, Col %2\$d",
        editorSelected = "%1\$d selected",
        previewTitle = "Preview",
        previewSubtitle = "Live HTML/CSS/JS",
        previewEmpty = "Empty document",
        previewBackToEditor = "Back to editor",
        previewReload = "Reload preview",
        previewLiveToggle = "Live refresh",
        previewConsole = "Console",
        previewConsoleEmpty = "No console output",
        previewClearConsole = "Clear console",
        previewShare = "Share HTML",
        previewShareFailed = "Share failed",
        previewOpenExternal = "Open in browser",
        previewDesktopView = "Desktop view",
        previewMobileView = "Mobile view",
        previewMarkdown = "Markdown preview",
        previewNoPreview = "No preview available for this file type",
        settingsTitle = "Settings",
        settingsAppearance = "Appearance",
        settingsLanguage = "Language",
        settingsLanguageDesc = "App interface language",
        settingsTheme = "Theme",
        settingsThemeSystem = "System",
        settingsThemeDark = "Dark",
        settingsThemeLight = "Light",
        settingsDynamicColor = "Dynamic color (Android 12+)",
        settingsDynamicColorDesc = "Use the system palette if available",
        settingsEditor = "Editor",
        settingsFontSize = "Font size",
        settingsTabSize = "Tab size",
        settingsTabSizeValue = "%1\$d spaces",
        settingsWordWrap = "Word wrap",
        settingsWordWrapDesc = "Wrap long lines instead of horizontal scroll",
        settingsLineNumbers = "Show line numbers",
        settingsLineNumbersDesc = "Display the gutter column on the left",
        settingsAutoIndent = "Auto indent",
        settingsAutoIndentDesc = "Match the previous line's indentation",
        settingsAutoSave = "Auto save",
        settingsAutoSaveDesc = "Save dirty files after a short idle delay",
        settingsAutoSaveDelay = "Auto-save delay",
        settingsFontFamily = "Editor font family",
        settingsStorage = "Storage (offline)",
        settingsUseLocalWorkspace = "Use local workspace",
        settingsUseLocalWorkspaceDesc = "Create a default offline workspace inside the app's private storage so ViperCode works without picking a folder",
        settingsHiddenFiles = "Show hidden files",
        settingsHiddenFilesDesc = "Reveal files and folders starting with a dot",
        settingsAutoCloseBrackets = "Auto-close brackets",
        settingsAutoCloseBracketsDesc = "Auto-insert closing brackets and quotes",
        settingsShowStatusBar = "Show status bar",
        settingsShowStatusBarDesc = "Display line/word/char count at the bottom",
        aboutTitle = "About",
        aboutDescription = "A modern, performant code editor for Android. Built for developers who demand the class of perfection in every keystroke.",
        aboutFeatures = "Features",
        aboutTechStack = "Tech stack",
        aboutVersion = "Version",
        aboutBuild = "Build",
        aboutDeveloper = "Developer",
        aboutLicense = "License",
        aboutSource = "Source",
        aboutFeature1 = "Multi-language syntax highlighting (30+ languages)",
        aboutFeature2 = "Multi-tab editing with dirty-state tracking",
        aboutFeature3 = "Storage Access Framework integration",
        aboutFeature4 = "Material 3 dynamic theming (Android 12+)",
        aboutFeature5 = "Optimised for Android 7.1.1+ (API 25)",
        aboutFeature6 = "Word wrap, line numbers, auto-indent",
        aboutFeature7 = "Find & Replace with regex + case toggle",
        aboutFeature8 = "Live HTML/CSS/JS preview via WebView",
        aboutFeature9 = "Cursor position persistence across tab switches",
        aboutFeature10 = "Vietnamese language support",
        aboutFeature11 = "Multi-file workspace search",
        aboutFeature12 = "Quick open + Go-to-line",
        aboutFeature13 = "Hidden files toggle + sort options",
        aboutFeature14 = "Auto-refresh preview with debounce",
        aboutFeature15 = "Auto-close brackets & quotes",
        aboutFeature16 = "Live Markdown preview",
        aboutFeature17 = "JavaScript console overlay in preview",
        aboutFeature18 = "Recent files, share & comment toggle",
        errorCreateFile = "Could not create file",
        errorCreateFolder = "Could not create folder",
        errorLoadFile = "Could not load file",
        errorSaveFile = "Could not save file",
        errorInvalidLine = "Invalid line number",
        errorRenameFailed = "Rename failed",
        errorDeleteFailed = "Delete failed",
        errorDuplicateFailed = "Duplicate failed",
        commonOk = "OK",
        commonFiles = "files",
        commonFolders = "folders",
        commonSortByName = "Sort by name",
        commonSortBySize = "Sort by size",
        commonSortByModified = "Sort by modified",
        commonShowHiddenFiles = "Show hidden files",
        commonHideHiddenFiles = "Hide hidden files",
        commonNoResults = "No results",
        commonMatchInFile = "%1\$d match(es) in %2\$s",
    )

    private val VIETNAMESE = T(
        appName = "ViperCode",
        tagline = "Đẳng cấp hoàn hảo",
        splashLoading = "Đang khởi tạo không gian làm việc…",
        homeNoFolder = "Chưa mở thư mục nào",
        homePickFolder = "Chọn một thư mục để bắt đầu code",
        homeNewFile = "Tạo tệp mới",
        homeNewFolder = "Tạo thư mục mới",
        homeNewFileHere = "Tạo tệp tại đây",
        homeNewFolderHere = "Tạo thư mục tại đây",
        homeRefresh = "Làm mới",
        homeOpenFolderSaf = "Mở thư mục (SAF)",
        homeUseLocalWorkspace = "Dùng thư mục cục bộ",
        homeSettings = "Cài đặt",
        homeAbout = "Giới thiệu ViperCode",
        homeRecent = "Vừa mở",
        homeNoRecent = "Chưa có tệp nào vừa mở",
        homeClearRecent = "Xoá danh sách vừa mở",
        homeUploadZip = "Tải ZIP lên để giải nén",
        homeSwitchFolder = "Đổi thư mục",
        homeProjects = "Dự án",
        homeNoProjects = "Chưa có dự án nào được giải nén",
        homeFolderSectionWorkspace = "Workspace",
        homeFolderSectionProjects = "Dự án đã giải nén",
        homeFolderSectionRecent = "Thư mục gần đây",
        homeFolderSectionDevice = "Duyệt thiết bị",
        homeBrowseDevice = "Duyệt bộ nhớ thiết bị",
        homeExtractingZip = "Đang giải nén ZIP…",
        homeZipExtracted = "Đã giải nén vào %1\$s",
        homeZipExtractFailed = "Giải nén ZIP thất bại",
        homeZipInvalid = "Tệp được chọn không phải là ZIP hợp lệ",
        homeEmptyFolder = "Thư mục này trống",
        homeEmptyFolderHint = "Dùng nút + để tạo tệp hoặc thư mục mới",
        homeCurrentFolder = "Thư mục hiện tại",
        dialogNewFileTitle = "Tệp mới",
        dialogNewFileHint = "vd: main.kt",
        dialogNewFolderTitle = "Thư mục mới",
        dialogNewFolderHint = "vd: src",
        dialogChooseAction = "Chọn hành động",
        dialogRename = "Đổi tên",
        dialogDelete = "Xoá",
        dialogDuplicate = "Nhân bản",
        dialogCreate = "Tạo",
        dialogCancel = "Huỷ",
        dialogConfirmDelete = "Xoá \"%1\$s\"?",
        dialogUnsavedTitle = "Chưa lưu thay đổi",
        dialogUnsavedBody = "Lưu trước khi đóng?",
        dialogSave = "Lưu",
        dialogDiscard = "Bỏ qua",
        dialogGoToLineTitle = "Nhảy tới dòng",
        dialogGoToLineHint = "Số dòng",
        dialogQuickOpenTitle = "Mở nhanh",
        dialogSearchInFilesTitle = "Tìm trong tệp",
        dialogSearchInFilesHint = "Nội dung tìm",
        editorEmpty = "Mở hoặc tạo tệp để bắt đầu soạn thảo",
        editorSave = "Lưu",
        editorSaved = "Đã lưu",
        editorSaveFailed = "Lưu thất bại",
        editorSearch = "Tìm",
        editorLivePreview = "Xem trước trực tiếp",
        editorBack = "Quay lại",
        editorCloseTab = "Đóng tab",
        editorReadOnly = "chỉ đọc",
        editorFind = "Tìm",
        editorReplace = "Thay thế",
        editorReplaceAll = "Tất cả",
        editorReplaceCurrent = "Thay kết quả này",
        editorNoMatchToReplace = "Không có kết quả để thay",
        editorNoMatchesToReplace = "Không có kết quả nào để thay",
        editorPreviousMatch = "Kết quả trước",
        editorNextMatch = "Kết quả sau",
        editorCloseSearch = "Đóng ô tìm kiếm",
        editorReplacedMatchN = "Đã thay kết quả %1\$d",
        editorReplacedNOccurrences = "Đã thay %1\$d lần xuất hiện",
        editorGoToLine = "Nhảy tới dòng",
        editorQuickOpen = "Mở nhanh",
        editorSearchInFiles = "Tìm trong tệp",
        editorWordWrap = "Tự động xuống dòng",
        editorShowLineNumbers = "Hiện số dòng",
        editorAutoIndent = "Tự động thụt lề",
        editorShare = "Chia sẻ tệp",
        editorShareFailed = "Chia sẻ thất bại",
        editorCommentToggle = "Bật/tắt ghi chú",
        editorUndo = "Hoàn tác",
        editorRedo = "Làm lại",
        editorLines = "Dòng",
        editorWords = "Từ",
        editorChars = "Ký tự",
        editorCursor = "Dòng %1\$d, Cột %2\$d",
        editorSelected = "Đã chọn %1\$d",
        previewTitle = "Xem trước",
        previewSubtitle = "HTML/CSS/JS trực tiếp",
        previewEmpty = "Tài liệu rỗng",
        previewBackToEditor = "Quay lại trình soạn thảo",
        previewReload = "Tải lại xem trước",
        previewLiveToggle = "Tự làm mới",
        previewConsole = "Bảng điều khiển",
        previewConsoleEmpty = "Chưa có log nào",
        previewClearConsole = "Xoá log",
        previewShare = "Chia sẻ HTML",
        previewShareFailed = "Chia sẻ thất bại",
        previewOpenExternal = "Mở trong trình duyệt",
        previewDesktopView = "Giao diện máy tính",
        previewMobileView = "Giao diện di động",
        previewMarkdown = "Xem trước Markdown",
        previewNoPreview = "Không có xem trước cho loại tệp này",
        settingsTitle = "Cài đặt",
        settingsAppearance = "Giao diện",
        settingsLanguage = "Ngôn ngữ",
        settingsLanguageDesc = "Ngôn ngữ giao diện ứng dụng",
        settingsTheme = "Chủ đề",
        settingsThemeSystem = "Hệ thống",
        settingsThemeDark = "Tối",
        settingsThemeLight = "Sáng",
        settingsDynamicColor = "Màu động (Android 12+)",
        settingsDynamicColorDesc = "Dùng bảng màu hệ thống nếu có",
        settingsEditor = "Trình soạn thảo",
        settingsFontSize = "Cỡ chữ",
        settingsTabSize = "Độ rộng Tab",
        settingsTabSizeValue = "%1\$d khoảng trắng",
        settingsWordWrap = "Tự xuống dòng",
        settingsWordWrapDesc = "Cuốn dòng dài thay vì cuộn ngang",
        settingsLineNumbers = "Hiện số dòng",
        settingsLineNumbersDesc = "Hiển thị cột số dòng bên trái",
        settingsAutoIndent = "Tự thụt lề",
        settingsAutoIndentDesc = "Theo thụt lề của dòng trước đó",
        settingsAutoSave = "Tự động lưu",
        settingsAutoSaveDesc = "Lưu tệp chưa lưu sau một khoảng nghỉ",
        settingsAutoSaveDelay = "Độ trễ tự lưu",
        settingsFontFamily = "Font trình soạn thảo",
        settingsStorage = "Lưu trữ (ngoại tuyến)",
        settingsUseLocalWorkspace = "Dùng thư mục cục bộ",
        settingsUseLocalWorkspaceDesc = "Tạo một thư mục mặc định trong bộ nhớ riêng của ứng dụng để ViperCode dùng được ngay mà không cần chọn thư mục",
        settingsHiddenFiles = "Hiện tệp ẩn",
        settingsHiddenFilesDesc = "Hiển thị tệp và thư mục bắt đầu bằng dấu chấm",
        settingsAutoCloseBrackets = "Tự đóng ngoặc",
        settingsAutoCloseBracketsDesc = "Tự chèn ngoặc đóng và dấu ngoặc kép",
        settingsShowStatusBar = "Hiện thanh trạng thái",
        settingsShowStatusBarDesc = "Hiển thị số dòng/từ/ký tự ở dưới cùng",
        aboutTitle = "Giới thiệu",
        aboutDescription = "Trình soạn thảo code Android hiện đại, mượt mà. Dành cho những lập trình viên đòi hỏi đẳng cấp hoàn hảo trong từng phím gõ.",
        aboutFeatures = "Tính năng",
        aboutTechStack = "Tech stack",
        aboutVersion = "Phiên bản",
        aboutBuild = "Build",
        aboutDeveloper = "Tác giả",
        aboutLicense = "Giấy phép",
        aboutSource = "Mã nguồn",
        aboutFeature1 = "Tô màu cú pháp 30+ ngôn ngữ lập trình",
        aboutFeature2 = "Mở nhiều tab cùng lúc, theo dõi trạng thái chưa lưu",
        aboutFeature3 = "Tích hợp Storage Access Framework",
        aboutFeature4 = "Tô màu động Material 3 (Android 12+)",
        aboutFeature5 = "Tối ưu cho Android 7.1.1+ (API 25)",
        aboutFeature6 = "Tự xuống dòng, số dòng, tự thụt lề",
        aboutFeature7 = "Tìm & Thay thế với regex + phân biệt hoa/thường",
        aboutFeature8 = "Xem trước HTML/CSS/JS trực tiếp qua WebView",
        aboutFeature9 = "Lưu vị trí con trỏ khi chuyển tab",
        aboutFeature10 = "Hỗ trợ tiếng Việt",
        aboutFeature11 = "Tìm kiếm toàn bộ workspace",
        aboutFeature12 = "Mở nhanh + Nhảy tới dòng",
        aboutFeature13 = "Bật tệp ẩn + tuỳ chọn sắp xếp",
        aboutFeature14 = "Tự làm mới xem trước có debounce",
        aboutFeature15 = "Tự đóng ngoặc & dấu ngoặc kép",
        aboutFeature16 = "Xem trước Markdown trực tiếp",
        aboutFeature17 = "Bảng console JavaScript trong xem trước",
        aboutFeature18 = "Tệp vừa mở, chia sẻ & bật/tắt ghi chú",
        errorCreateFile = "Không tạo được tệp",
        errorCreateFolder = "Không tạo được thư mục",
        errorLoadFile = "Không đọc được tệp",
        errorSaveFile = "Không lưu được tệp",
        errorInvalidLine = "Số dòng không hợp lệ",
        errorRenameFailed = "Đổi tên thất bại",
        errorDeleteFailed = "Xoá thất bại",
        errorDuplicateFailed = "Nhân bản thất bại",
        commonOk = "OK",
        commonFiles = "tệp",
        commonFolders = "thư mục",
        commonSortByName = "Sắp theo tên",
        commonSortBySize = "Sắp theo kích thước",
        commonSortByModified = "Sắp theo thời gian",
        commonShowHiddenFiles = "Hiện tệp ẩn",
        commonHideHiddenFiles = "Ẩn tệp ẩn",
        commonNoResults = "Không có kết quả",
        commonMatchInFile = "%1\$d kết quả trong %2\$s",
    )

    private val STRINGS: Map<Language, T> = mapOf(
        Language.ENGLISH to ENGLISH,
        Language.VIETNAMESE to VIETNAMESE,
    )

    private val _active = MutableStateFlow(Language.ENGLISH)
    val active: StateFlow<Language> = _active

    /** Returns the current catalogue. Compose callers should observe [active] first. */
    fun get(): T = STRINGS[_active.value] ?: ENGLISH

    /** Switches the active language at runtime. */
    fun setLanguage(lang: Language) {
        _active.value = lang
    }

    /** Resolves a [SettingsRepository.LanguageMode] pref to a [Language]. */
    fun applyMode(mode: SettingsRepository.LanguageMode) {
        _active.value = when (mode) {
            SettingsRepository.LanguageMode.SYSTEM -> {
                val lang = java.util.Locale.getDefault().language
                if (lang == "vi") Language.VIETNAMESE else Language.ENGLISH
            }
            SettingsRepository.LanguageMode.ENGLISH -> Language.ENGLISH
            SettingsRepository.LanguageMode.VIETNAMESE -> Language.VIETNAMESE
        }
    }
}
